"""Strategy 3 - Phi EMA Cascade.

A trend follower whose entire parameterisation is generated by the
golden mean. Moving-average spans are consecutive powers of phi
(round(phi^k) for k = 3..8 -> 4, 7, 11, 18, 29, 47), so each timescale
views the market ~61.8% faster than the next - a self-similar cascade
rather than an arbitrary fast/slow pair. Each adjacent EMA pair votes on
trend direction and the votes are blended with golden-decay weights
(1/phi^k, fastest pair weighted most). Exposure is the weighted vote
total, with a dead-band of 0.382 so the book stays flat when the cascade
disagrees with itself.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from golden_strategies.base import Strategy
from golden_strategies.indicators import PHI, ema


class PhiEmaCascadeStrategy(Strategy):
    __doc__ = __doc__

    name = "phi_ema_cascade"

    def __init__(self, powers: tuple[int, ...] = (3, 4, 5, 6, 7, 8), dead_band: float = 0.382):
        self.spans = [max(2, round(PHI**k)) for k in powers]
        self.dead_band = dead_band

    def target_positions(self, df: pd.DataFrame) -> pd.Series:
        close = df["close"]
        emas = [ema(close, span) for span in self.spans]

        raw_weights = np.array([PHI**-k for k in range(len(emas) - 1)])
        weights = raw_weights / raw_weights.sum()

        vote = pd.Series(0.0, index=df.index)
        for w, fast, slow in zip(weights, emas[:-1], emas[1:]):
            vote = vote + w * np.sign(fast - slow)

        position = vote.where(vote.abs() >= self.dead_band, 0.0)
        # Suppress signals during the warmup of the slowest EMA.
        position.iloc[: max(self.spans)] = 0.0
        return position.clip(-1.0, 1.0).rename(self.name)
